apiVersion: v1
kind: ConfigMap
metadata:
  name: demobuilder-config
  namespace: demobuilder
  labels:
    app: demobuilder
    component: config
data:
  # Application configuration
  app_title: "DemoBuilder - Infrastructure Assistant"
  max_conversation_turns: "50"
  anthropic_model: "claude-3-5-sonnet-20241022"
  
  # Feature flags
  redis_enabled: "false"
  keycloak_enabled: "false"
  
  # Streamlit configuration
  streamlit_server_port: "8501"
  streamlit_server_address: "0.0.0.0"
  streamlit_server_headless: "true"
  streamlit_server_enable_cors: "false"
  streamlit_server_enable_xsrf_protection: "false"
  
  # Logging
  log_level: "INFO"