apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobuilder
  namespace: demobuilder
  labels:
    app: demobuilder
    component: web-app
    version: v1.0.0b5
    logging: enabled
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demobuilder
      component: web-app
  template:
    metadata:
      labels:
        app: demobuilder
        component: web-app
        version: v1.0.0b5
        logging: enabled
      annotations:
        prometheus.io/scrape: "false"
        fluentd.io/log-driver: "json-file"
        logging.openshift.io/collect: "true"
    spec:
      serviceAccountName: demobuilder
      securityContext:
        runAsNonRoot: true
      containers:
      - name: demobuilder
        image: image-registry.openshift-image-registry.svc:5000/demobuilder/demobuilder:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        env:
        # Configuration from ConfigMap
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: app_title
        - name: MAX_CONVERSATION_TURNS
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: max_conversation_turns
        - name: ANTHROPIC_MODEL
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: anthropic_model
        - name: REDIS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: redis_enabled
        - name: KEYCLOAK_ENABLED
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: keycloak_enabled
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: log_level
        
        # OpenShift environment variables for logging context
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEPLOYMENT_NAME
          value: "demobuilder"
        - name: APP_VERSION
          value: "v1.0.0b5"
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: demobuilder-config
              key: cluster_name
              optional: true
        
        # Secrets
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: demobuilder-secrets
              key: anthropic-api-key
              optional: true
        # - name: REDIS_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: demobuilder-secrets
        #       key: redis-url
        #       optional: true
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30