apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demobuilder-openshift
  annotations:
    description: "DemoBuilder OpenShift deployment configuration"

namespace: demobuilder

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- route.yaml
- networkpolicy.yaml
- horizontalpodautoscaler.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: demobuilder
    app.kubernetes.io/instance: demobuilder-prod
    app.kubernetes.io/version: v1.0.0b5
    app.kubernetes.io/component: infrastructure-assistant
    app.kubernetes.io/part-of: yamlforge
    app.kubernetes.io/managed-by: kustomize

images:
- name: demobuilder
  newName: demobuilder
  newTag: latest

configMapGenerator:
- name: demobuilder-build-info
  literals:
  - build.date=BUILD_DATE
  - build.version=BUILD_VERSION
  - build.commit=BUILD_COMMIT

patches:
- target:
    kind: Deployment
    name: demobuilder
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations/config.hash
      value: CONFIG_HASH
    - op: add
      path: /spec/template/metadata/annotations/build.date
      value: BUILD_DATE

replicas:
- name: demobuilder
  count: 2