apiVersion: v1
kind: Secret
metadata:
  name: demobuilder-secrets
  namespace: demobuilder
  labels:
    app: demobuilder
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets
  # To create: echo -n "your-api-key" | base64
  
  # Anthropic API key (optional - for enhanced features)
  # anthropic-api-key: ""
  
  # Redis connection (optional - for session persistence)
  # redis-url: ""
  
  # Keycloak configuration (future use)
  # keycloak-server-url: ""
  # keycloak-realm: ""
  # keycloak-client-id: ""
  # keycloak-client-secret: ""

---
# Example of how to create secrets via command line:
# oc create secret generic demobuilder-secrets \
#   --from-literal=anthropic-api-key="your-api-key" \
#   --from-literal=redis-url="redis://redis:6379" \
#   -n demobuilder