apiVersion: v1
kind: ServiceAccount
metadata:
  name: demobuilder
  namespace: demobuilder
  labels:
    app: demobuilder
    component: service-account
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.demobuilder: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"demobuilder"}}'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demobuilder
  namespace: demobuilder
  labels:
    app: demobuilder
    component: rbac
rules:
# Read access to ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
# Read access to own pods (for health checks)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Future: CNV integration permissions
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances"]
  verbs: ["get", "list"]
  resourceNames: [] # Restrict to specific resources if needed

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demobuilder
  namespace: demobuilder
  labels:
    app: demobuilder
    component: rbac
subjects:
- kind: ServiceAccount
  name: demobuilder
  namespace: demobuilder
roleRef:
  kind: Role
  name: demobuilder
  apiGroup: rbac.authorization.k8s.io