version: '3.8'

services:
  demobuilder:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: demobuilder
    ports:
      - "8501:8501"
    environment:
      # Application configuration
      - APP_TITLE=DemoBuilder - Infrastructure Assistant
      - MAX_CONVERSATION_TURNS=50
      - ANTHROPIC_MODEL=claude-3-5-sonnet-20241022
      
      # Feature flags
      - CONTEXT7_ENABLED=true
      - CONTEXT7_MCP_URL=https://mcp.context7.com/mcp
      - REDIS_ENABLED=false
      - KEYCLOAK_ENABLED=false
      
      # Optional: Add API keys via environment or .env file
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - REDIS_URL=redis://redis:6379
      
      # Logging
      - LOG_LEVEL=INFO
    
    volumes:
      # Optional: Mount configuration files
      # - ./config:/app/config:ro
      # Optional: Mount logs directory
      # - ./logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    user: "1001:1001"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Redis for session persistence (future feature)
  redis:
    image: redis:7-alpine
    container_name: demobuilder-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    profiles:
      - redis  # Only start with: docker-compose --profile redis up

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: demobuilder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - demobuilder
    restart: unless-stopped
    profiles:
      - nginx  # Only start with: docker-compose --profile nginx up

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: demobuilder-network