[server]
# Disable browser auto-open
headless = true

# Server configuration
port = 8501
address = "0.0.0.0"

# CORS settings for production
enableCORS = false
enableXsrfProtection = false
enableStaticServing = false

[browser]
# Disable browser auto-open
gatherUsageStats = false

[global]
# Development settings
developmentMode = false
showWarningOnDirectExecution = false

[client]
# Use viewer mode for production security (no developer options)
toolbarMode = "viewer"

[ui]
# Hide top bar since we have custom theme toggle
hideTopBar = true

[theme]
# Optional: Set a professional theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"